version: "3"

services:
  books-db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: Books
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5438:5432"
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d/
      - ./db/:/var/lib/postgresql/data